[package]
name = "blerepl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "10.0.0"
btleplug = { version = "0.10", features = ["serde"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
exitcode = "1.1.2"
clap = { version = "3.2.16", features = ["derive"]}
async-trait = "0.1.57"
futures = "0.3.21"
tokio = { version = "1.20.1", features = ["full"] }
comfy-table = "6.1.0"
